### ISSUE TITLE
Few changes required to improve your project-level

### ISSUE THREAD

**Issue by Malkhan52** [HarishTeens/Monday-Morning-Summer-Task#1]
No doubt u gave ur best.
But still, there are few minor or major changes required such as...

- subscribers also have access to admin panel
for this do one thing while opening admin page check access_level along with login.
this should be only admin to access the admin panel.
or can make a private function i**sAdmin()** and can call before loading admin panel.

- at home page articles should be according to the categories.
this can be done as,
make a select list for categories in add-new-article then show articles according to categories.

- Try to show date-time of published article

- Add **edit article** and **delete article** feature while **browse** all articles

**Comment by HarishTeens** [comment]
Thanks for suggesting these changes, all of them are resolved. :D
