### ISSUE TITLE
Table article store only image's name not complete address

### ISSUE THREAD

**Issue by Malkhan52** [HarishTeens/Monday-Morning-Summer-Task#2]
Then while showing image in articles,
use only name as php variable and rest address will be fixed as
`src = "<?php echo base_url('assets/img/uploads/') .$img_name.;?>"`
or `src = "<?php echo base_url('assets/img/uploads/'); ?><?php echo $img_name;?>"`

**Comment by HarishTeens** [comment]
Done the required change, now only the image name is stored in the database, not the whole address
